---
apiVersion: v1
kind: Namespace
metadata:
  name: registry
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: registry-ingress
  namespace: registry
  annotations:
    kubernetes.io/ingress.class: "traefik"
    traefik.ingress.kubernetes.io/router.middlewares: kube-system-ssl-redirect@kubernetescrd
spec:
  rules:
    - http:
        paths:
          - path: /v2/
            pathType: Prefix
            backend:
              service:
                name: kevin-docker-registry
                port:
                  number: 5000
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: kevin
  namespace: registry
spec:
  chart: https://%{KUBERNETES_API}%/static/charts/docker-registry-1.10.1.tgz
  targetNamespace: registry
  valuesContent: |-
    persistence:
      size: 128Gi
      enabled: true
    image:
      repository: registry
      tag: "2"
      pullPolicy: Never
    secrets:
      htpasswd: ###ZARF_HTPASSWD###
    resources:
      requests:
        cpu: "100m"
        memory: "512Mi"
      limits:
        cpu: "1"
        memory: "2Gi"
